# Generated by Django 2.0 on 2021-09-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='Email', max_length=100)),
                ('Password', models.CharField(default='Password', max_length=100)),
                ('Role', models.CharField(default='Role', max_length=100)),
                ('Department', models.CharField(default='Depaetment', max_length=100)),
                ('Salary', models.BigIntegerField(default=10000)),
                ('Fotp', models.BigIntegerField(default=123456)),
                ('t_c', models.BooleanField(default=False)),
                ('Is_Created', models.DateTimeField(auto_now_add=True)),
                ('Is_Activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='Firstname', max_length=100)),
                ('Lastname', models.CharField(default='Lastname', max_length=100)),
                ('Gender', models.CharField(default='Gender', max_length=100)),
                ('Address', models.CharField(default='Address', max_length=100)),
                ('Phone', models.BigIntegerField(default=1234567890)),
                ('Bdate', models.DateField(auto_now_add=True)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='Firstname', max_length=100)),
                ('Lastname', models.CharField(default='Lastname', max_length=100)),
                ('Gender', models.CharField(default='Gender', max_length=100)),
                ('Address', models.CharField(default='Address', max_length=100)),
                ('Phone', models.BigIntegerField(default=1234567890)),
                ('Bdate', models.DateField(auto_now_add=True)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='Firstname', max_length=100)),
                ('Lastname', models.CharField(default='Lastname', max_length=100)),
                ('Gender', models.CharField(default='Gender', max_length=100)),
                ('Address', models.CharField(default='Address', max_length=100)),
                ('Phone', models.BigIntegerField(default=1234567890)),
                ('Bdate', models.DateField(auto_now_add=True)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
                ('Head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Head')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='HR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HR'),
        ),
    ]
