# Generated by Django 2.0 on 2021-09-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='Head',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
    ]
