# Generated by Django 2.0 on 2021-10-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_admin_t_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='HR',
        ),
    ]
