# Generated by Django 2.0 on 2021-10-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_requestname_requestsend'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(default='Reason', max_length=100)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('Em', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
                ('reqna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RequestName')),
            ],
        ),
        migrations.CreateModel(
            name='HrRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(default='Reason', max_length=100)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HR')),
                ('reqna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RequestName')),
            ],
        ),
        migrations.RemoveField(
            model_name='requestsend',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='requestsend',
            name='reqna',
        ),
        migrations.DeleteModel(
            name='Requestsend',
        ),
    ]
