# Generated by Django 2.0 on 2021-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211028_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrequest',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emrequest',
            name='startdate',
            field=models.DateField(),
        ),
    ]
