# Generated by Django 2.0 on 2021-10-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211029_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrequest',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hrrequest',
            name='startdate',
            field=models.DateField(),
        ),
    ]
